### ISSUE TITLE
OnChange usage

### ISSUE THREAD

**Issue by arthursoas** [Vlad-Zhukov/react-text-mask-hoc#3]
Could you give an example of usage of onChange prop? I'm trying using but without success. Thanks

**Comment by arthursoas** [comment]
In my situation, I need to set my state...

**Comment by vlad-zhukov** [comment]
Have a look at the [React](https://github.com/vlad-zhukov/react-text-mask-hoc/blob/master/examples/reactapp/src/App.js) example. TL;DR:

```js
import React from 'react';
import {TextMask, InputAdapter} from 'react-text-mask-hoc';

class App extends React.Component {
	myFieldMask = [/\d/, /\d/, /\d/];

	state = {
		myField: '123',
	};

	this._onChangeMyField = (event, {value}) => {
		this.setState({myField: value}); // you can use `event.target.value` instead
	};

	render() {
		return (
			<TextMask
				component={InputAdapter}
				value={this.state.myField}
				mask={this.myFieldMask}
				guide={false}
				onChange={this._onChangeMyField}
		 	/>
		);
	}
}
```

**Comment by arthursoas** [comment]
Thanks, it worked.
A problem I noticed: when guide is true, the component has a weird behavior. Looks like it loses the position of the cursor.

Look my field when I use your solution whit guide turned on:
(5_) 4_3_4-_5_4

Thanks for the fast answer!

**Comment by vlad-zhukov** [comment]
That's weird, huh!
