### ISSUE TITLE
Using withFormik

### ISSUE THREAD

**Issue by si-huynh** [Vlad-Zhukov/react-text-mask-hoc#4]
How I can integrate with formik to validate value

**Comment by vlad-zhukov** [comment]
Basically the same way you would do with a plain `input`, `react-text-mask-hoc` doesn't do any validation.

A very simple example:
```js
import React from 'react';
import {Formik} from 'formik';
import {TextMask, InputAdapter} from 'react-text-mask-hoc';

const phoneMask = [
  "(",
  /[1-9]/,
  /\d/,
  /\d/,
  ")",
  " ",
  /\d/,
  /\d/,
  /\d/,
  "-",
  /\d/,
  /\d/,
  /\d/,
  /\d/
];


const initialValues = {foo: ''};

export default () => (
	<Formik initialValues={initialValues} render={({values, handleChange}) => (
		<TextMask
        	Component={InputAdapter}
            value={values.foo}
            mask={phoneMask}
            guide={false}
            onChange={handleChange('foo')}
            onBlur={handleBlur('foo')}
        />
	)} />
);
```

**Comment by si-huynh** [comment]
Thank you for feedback, I do it easily but it's not using validation in withFormik & Yup schema. FormFeedback doesn't show when value is invalid.
<img width="1121" alt="screen shot 2018-10-07 at 10 13 16 pm" src="https://user-images.githubusercontent.com/3185782/46583286-858b7780-ca7e-11e8-8c82-0f396af5b1df.png">
