### ISSUE TITLE
Repeat parts in regex mask

### ISSUE THREAD

**Issue by Valerika** [Vlad-Zhukov/react-text-mask-hoc#6]
Hi! Is it possible to make such a combination of characters?
`(([\d\D]{5})([-]{1})){9}` for the next check `x4294-24H20-40j49-02d42-49s94-49292-49920-99222-24393`
Not working for me :(
Thanks!

**Comment by vlad-zhukov** [comment]
Hi! Your regexp doesn't match such strings because it requires an additional `-` at the end. Also `\D` matches all characters that are not digits including emojis and `-` too. 😃 

I'd probably do it like that:
```jsx
const fiveChars = new Array(5).fill(/[a-zA-Z\d]/);
const mask = new Array(9).fill().reduce((res, _, index) => {
	res.push(...fiveChars);
	if (index !== 8) {
		res.push('-');
	}
	return res;
}, []);

// Inside component:
;<TextMask mask={mask} />
```

Have a nice day!

**Comment by Valerika** [comment]
Vlad, thanks for the help!!! ❤️❤️❤️
Have a nice day too!🌞
